cabal-version:      3.4
name:               simdy
version:            0.1.0.0
synopsis:           Wrappers around GHC's SIMD primitives.
description:        Please see the README on GitHub at <https://github.com/minoki/haskell-simdy#readme>
license:            BSD-3-Clause
license-file:       LICENSE
author:             ARATA Mizuki
maintainer:         minorinoki@gmail.com
copyright:          2026 ARATA Mizuki
category:           Data
build-type:         Simple
extra-doc-files:    README.md
                    CHANGELOG.md
extra-source-files: cbits/mask.h

-- The versions of GHC and core libraries:
--
-- * GHC 9.8.* / base-4.19.* / ghc-prim 0.11.*
--     * GHC 9.8.1 and 9.8.2 are not supported because the FMA primitive is broken and I don't think it is worth working around it.
--     * GHC 9.8.1 is affected by: https://gitlab.haskell.org/ghc/ghc/-/issues/24160
--     * GHC 9.8.2 is affected by: https://gitlab.haskell.org/ghc/ghc/-/issues/24496
--     * __GLASGOW_HASKELL_LLVM__ issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25606
--     * FFI issue on AArch64: https://gitlab.haskell.org/ghc/ghc/-/issues/26907
--     * Stack alignment issue on x86: https://gitlab.haskell.org/ghc/ghc/-/issues/26595, https://gitlab.haskell.org/ghc/ghc/-/issues/26822
-- * GHC 9.10.* / base-4.20.* / ghc-prim 0.12.*
--     * __GLASGOW_HASKELL_LLVM__ issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25606, fixed in 9.10.2
--     * FFI issue on AArch64: https://gitlab.haskell.org/ghc/ghc/-/issues/26907
--     * Stack alignment issue on x86: https://gitlab.haskell.org/ghc/ghc/-/issues/26595, https://gitlab.haskell.org/ghc/ghc/-/issues/26822
-- * GHC 9.12.* / base-4.21.* / ghc-prim 0.13.* / ghc-internal 9.12##.* / ghc-experimental 9.12##.*
--     * GHC 9.12.{1,2,3} are not supported because of multiple issues.
--     * Broadcast issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25561, fixed in 9.12.3
--     * __GLASGOW_HASKELL_LLVM__ issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25606, fixed in 9.12.3
--     * FFI issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25730, fixed in 9.12.3
--     * +evex512 issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26410, fixed in 9.12.4
--     * NCG spill issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26411, fixed in 9.12.4
--     * Stack alignment issue on x86: https://gitlab.haskell.org/ghc/ghc/-/issues/26595, https://gitlab.haskell.org/ghc/ghc/-/issues/26822
-- * GHC 9.14.* / base-4.22.* / ghc-prim 0.13.* / ghc-internal 9.14##.* / ghc-experimental 9.14##.*
--     * I'd like to drop support for 9.14.1 once 9.14.2 is out, because of +evex512 and NCG spill issue.
--     * +evex512 issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26410
--     * NCG spill issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26411
--     * Stack alignment issue on x86: https://gitlab.haskell.org/ghc/ghc/-/issues/26595, https://gitlab.haskell.org/ghc/ghc/-/issues/26822

flag no-simd
    description: Don't use native vector types
    manual: True
    default: False

-- Setting the `avx512` flag should enable the functionality of `haswell`.
-- To achieve this, we should use `flag(haswell) || flag(avx512)` instead of just `flag(haswell)`
flag haswell
    description: Enable AVX2+FMA+F16C (Intel: Haswell or later, AMD: Zen or later). Try to use 256-bit vectors if supported by the backend.
    manual: True
    default: False

flag avx512
    description: Enable AVX-512 (F+VL+BW+DQ). Try to use 512-bit vectors if supported by the backend.
    manual: True
    default: False

flag llvm
    description: Use the LLVM backend
    manual: True
    default: True

common warnings
    ghc-options: -Wall -Wcompat
    if impl(ghc >= 9.14)
        -- For Data.Simdy.Tuple
        ghc-options: -Wno-pattern-namespace-specifier

common ghc-support
    if impl(ghc == 9.8.1) || impl(ghc == 9.8.2)
        -- GHC 9.8.1 has the FMA primitive broken: https://gitlab.haskell.org/ghc/ghc/-/issues/24160
        -- GHC 9.8.2 has the FMA primitive broken: https://gitlab.haskell.org/ghc/ghc/-/issues/24496
        buildable: False
    if impl(ghc == 9.10.1)
        -- Broken because of __GLASGOW_HASKELL_LLVM__ issue
        buildable: False
    if impl(ghc == 9.12.1) || impl(ghc == 9.12.2) || impl(ghc == 9.12.3)
        -- Broken because of multiple issues
        buildable: False

common arch-options
    if flag(haswell) || flag(avx512)
        -- Traditionally, -mavx didn't imply -msse4.2: https://gitlab.haskell.org/ghc/ghc/-/issues/24989
        -- GHC 10.0 introduces the new behavior.
        ghc-options: -msse4.2 -mavx -mavx2 -mfma
        cc-options: -mavx2 -mfma -mf16c
    if flag(haswell) || flag(avx512) || arch(aarch64)
        cpp-options: -DUSE_FMA
    if flag(avx512)
        ghc-options: -mavx512f
        if impl(ghc >= 9.15)
            -- New feature in GHC 10.0: https://gitlab.haskell.org/ghc/ghc/-/issues/26406
            ghc-options: -mavx512vl -mavx512bw -mavx512dq
        else
            ghc-options: -optlc -mattr=+avx512bw,+avx512dq,+avx512vl
        cpp-options: -DUSE_AVX512
        cc-options: -mavx512f -mavx512vl -mavx512bw -mavx512dq

library common
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy.Fusible
                      Data.Simdy.Internal.Bits
                      Data.Simdy.Internal.Class
                      Data.Simdy.Internal.Shuffle
    other-modules:    Data.Simdy.Internal.Class.Generated
                      Data.Simdy.Internal.FMA

    c-sources:        cbits/float_minmax.c
                      cbits/float_minmaxnm.c
                      cbits/double_minmax.c
                      cbits/double_minmaxnm.c

    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0
    hs-source-dirs:   src-common
    default-language: GHC2021

library no-simd
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.NoSIMD
    other-modules:    Data.Simdy.Internal.NoSIMD.X2
                      Data.Simdy.Internal.NoSIMD.X4
                      Data.Simdy.Internal.NoSIMD.X8
                      Data.Simdy.Internal.NoSIMD.X16
                      Data.Simdy.Internal.NoSIMD.X32
                      Data.Simdy.Internal.NoSIMD.X64
                      Data.Simdy.Internal.NoSIMD.HalfVector
    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0,
                      simdy:common
    hs-source-dirs:   src-no-simd
    default-language: GHC2021

library vl128-c
    if flag(haswell) || flag(avx512)
        cc-options:   -mavx2 -mfma -mf16c
    if flag(avx512)
        cc-options:   -mavx512f -mavx512vl -mavx512bw -mavx512dq
    c-sources:        cbits/bitwise_vl128.c
                      cbits/double_compare_vl128.c
                      cbits/double_minmax_vl128.c
                      cbits/double_minmaxnm_vl128.c
                      cbits/float_compare_vl128.c
                      cbits/float_minmax_vl128.c
                      cbits/float_minmaxnm_vl128.c
                      cbits/int_abs_vl128.c
                      cbits/int_compare_vl128.c
                      cbits/int_minmax_vl128.c
                      cbits/mask_vl128.c
                      cbits/select_vl128.c

library vl128
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.VL128
                      Data.Simdy.Internal.VL128.Prim
                      Data.Simdy.Internal.VL128.PrimExtra
    other-modules:    Data.Simdy.Internal.VL128.X2
                      Data.Simdy.Internal.VL128.X4
                      Data.Simdy.Internal.VL128.X8
                      Data.Simdy.Internal.VL128.X16
                      Data.Simdy.Internal.VL128.X32
                      Data.Simdy.Internal.VL128.X64
                      Data.Simdy.Internal.VL128.HalfVector
    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0,
                      simdy:common,
                      simdy:vl128-c
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl128
    default-language: GHC2021

    if flag(llvm) || !((impl(ghc >= 9.12) && arch(x86_64)) || (impl(ghc >= 9.15) && arch(aarch64)))
        -- We need the LLVM backend unless (ghc >= 9.12 && x86_64) || (ghc >= 10.0 && aarch64)
        ghc-options: -fllvm

        if impl(ghc < 9.10) || impl(ghc == 9.10.1)
            -- Detection of LLVM is broken on GHC 9.8, so __GLASGOW_HASKELL_LLVM__ is not defined
            cpp-options: -DUSE_LLVM

    if arch(x86_64) && !flag(llvm) && impl(ghc < 9.12)
        -- x86_64:
        -- * GHC >= 9.8 with LLVM
        -- * GHC >= 9.12 with NCG
        buildable: False

    if arch(aarch64) && (flag(llvm) && impl(ghc < 9.12) || !flag(llvm) && impl(ghc < 9.15))
        -- AArch64:
        --   * GHC >= 9.12 with LLVM
        --   * GHC >= 10.0 with NCG
        buildable: False

library vl256-c
    cc-options:       -mavx2 -mfma -mf16c
    if flag(avx512)
        cc-options:   -mavx512f -mavx512vl -mavx512bw -mavx512dq
    c-sources:        cbits/bitwise_vl256.c
                      cbits/double_compare_vl256.c
                      cbits/double_minmax_vl256.c
                      cbits/double_minmaxnm_vl256.c
                      cbits/float_compare_vl256.c
                      cbits/float_minmax_vl256.c
                      cbits/float_minmaxnm_vl256.c
                      cbits/int_compare_vl256.c
                      cbits/int_minmax_vl256.c
                      cbits/mask_vl256.c
                      cbits/select_vl256.c

library vl256
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.VL256
                      Data.Simdy.Internal.VL256.Prim
                      Data.Simdy.Internal.VL256.PrimExtra
    other-modules:    Data.Simdy.Internal.VL256.X4
                      Data.Simdy.Internal.VL256.X8
                      Data.Simdy.Internal.VL256.X16
                      Data.Simdy.Internal.VL256.X32
                      Data.Simdy.Internal.VL256.X64
                      Data.Simdy.Internal.VL256.HalfVector
    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0,
                      simdy:common,
                      simdy:vl128,
                      simdy:vl256-c
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl256
    default-language: GHC2021

    -- We need the LLVM backend, so just enable it
    ghc-options: -fllvm

    if !flag(llvm) || !(flag(haswell) || flag(avx512))
        -- vl256 requires (haswell || avx512) && llvm
        buildable: False

library vl512-c
    cc-options:       -mavx2 -mfma -mf16c -mavx512f -mavx512vl -mavx512bw -mavx512dq
    c-sources:        cbits/bitwise_vl512.c
                      cbits/double_compare_vl512.c
                      cbits/double_minmax_vl512.c
                      cbits/double_minmaxnm_vl512.c
                      cbits/float_compare_vl512.c
                      cbits/float_minmax_vl512.c
                      cbits/float_minmaxnm_vl512.c
                      cbits/int_compare_vl512.c
                      cbits/int_minmax_vl512.c
                      cbits/select_vl512.c

library vl512
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.VL512
                      Data.Simdy.Internal.VL512.Prim
                      Data.Simdy.Internal.VL512.PrimExtra
    other-modules:    Data.Simdy.Internal.VL512.X8
                      Data.Simdy.Internal.VL512.X16
                      Data.Simdy.Internal.VL512.X32
                      Data.Simdy.Internal.VL512.X64
                      Data.Simdy.Internal.VL512.HalfVector
    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0,
                      simdy:common,
                      simdy:vl128,
                      simdy:vl256,
                      simdy:vl512-c
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl512
    default-language: GHC2021

    -- We need the LLVM backend, so just enable it
    ghc-options: -fllvm

    if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
        -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
        -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
        ghc-options: -optlc -mattr=+evex512

    if flag(avx512) && os(windows) && (impl(ghc == 9.8.3) || impl(ghc == 9.8.4) || impl(ghc == 9.10.2) || impl(ghc == 9.10.3) || impl(ghc == 9.12.4) || impl(ghc == 9.14.1))
        -- The stack alignment issue is critical on Windows
        buildable: False

    if !flag(llvm) || !flag(avx512)
        -- vl512 requires avx512 && llvm
        buildable: False

library plugin
    import:           warnings
                    , ghc-support
                    , arch-options
    visibility:       public
    exposed-modules:  Data.Simdy.Shuffle.Plugin
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy:common,
                      ghc >=9.8 && <10.1,
                      ghc-tcplugin-api ^>=0.19
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-plugin
    default-language: GHC2021

library
    import:           warnings
                    , ghc-support
                    , arch-options
    exposed-modules:  Data.Simdy
                      Data.Simdy.Backend
                      Data.Simdy.Bits
                      Data.Simdy.FMA
                      Data.Simdy.Horizontal
                      Data.Simdy.Mask
                      Data.Simdy.MinMax
                      Data.Simdy.Pack
                      Data.Simdy.Shuffle
                      Data.Simdy.Split
                      Data.Simdy.Tuple
                      Data.Simdy.Vector.Bundle
                      Data.Simdy.Vector.Class
                      Data.Simdy.Vector.Generic
                      Data.Simdy.Vector.Unboxed
    reexported-modules: Data.Simdy.Fusible
                      , Data.Simdy.Internal.Class
                      , Data.Simdy.Internal.NoSIMD

    if !flag(no-simd) && (flag(llvm) || (impl(ghc >= 9.12) && arch(x86_64)) || (impl(ghc >= 9.15) && arch(aarch64)))
        reexported-modules: Data.Simdy.Internal.VL128
        build-depends: simdy:vl128
    if !flag(no-simd) && (flag(haswell) || flag(avx512)) && flag(llvm)
        reexported-modules: Data.Simdy.Internal.VL256
        build-depends: simdy:vl256
    if !flag(no-simd) && flag(avx512) && flag(llvm)
        reexported-modules: Data.Simdy.Internal.VL512
        build-depends: simdy:vl512

    -- Choose the default vector length (Data.Simdy.Internal.Default) based on the flags.
    if flag(no-simd) || (!flag(llvm) && (impl(ghc < 9.12) || !arch(x86_64)) && (impl(ghc < 9.15) || !arch(aarch64)))
        mixins: simdy:no-simd (Data.Simdy.Internal.NoSIMD, Data.Simdy.Internal.NoSIMD as Data.Simdy.Internal.Default)
    elif flag(avx512) && flag(llvm)
        mixins: simdy:vl512 (Data.Simdy.Internal.VL512, Data.Simdy.Internal.VL512 as Data.Simdy.Internal.Default)
    elif flag(haswell) && flag(llvm)
        mixins: simdy:vl256 (Data.Simdy.Internal.VL256, Data.Simdy.Internal.VL256 as Data.Simdy.Internal.Default)
    else
        mixins: simdy:vl128 (Data.Simdy.Internal.VL128, Data.Simdy.Internal.VL128 as Data.Simdy.Internal.Default)

    -- other-extensions:
    build-depends:    base >=4.19.0.0 && <4.24,
                      primitive ^>=0.9.0.0,
                      vector ^>=0.13.1.0,
                      simdy:common,
                      simdy:no-simd
    hs-source-dirs:   src
    default-language: GHC2021

test-suite simdy-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1,
                      tasty-hunit ^>=0.10.2

    if flag(llvm)
        ghc-options: -fllvm

        if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
            -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
            -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
            ghc-options: -optlc -mattr=+evex512

test-suite shuffle-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test-shuffle
    main-is:          ShuffleTest.hs
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy,
                      simdy:plugin,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1,
                      tasty-hunit ^>=0.10.2
    ghc-options:      -dlint

    if flag(llvm)
        ghc-options: -fllvm

        if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
            -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
            -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
            ghc-options: -optlc -mattr=+evex512

test-suite float-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_float_minmax.c
    build-depends:    simdy,
                      simdy:vl128-c,
                      simdy:vl256-c,
                      simdy:vl512-c

test-suite double-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_double_minmax.c
    build-depends:    simdy,
                      simdy:vl128-c,
                      simdy:vl256-c,
                      simdy:vl512-c

library matmul
    import:           warnings
                    , arch-options
    exposed-modules:  MatMul
    hs-source-dirs:   example/matmul
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy,
                      simdy:plugin,
                      vector ^>=0.13.1.0,
                      deepseq
    default-language: GHC2021

    if flag(llvm)
        ghc-options: -fllvm

        if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
            -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
            -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
            ghc-options: -optlc -mattr=+evex512

test-suite simdy-test-matmul
    import:           warnings
                    , arch-options
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   example/matmul-test
    main-is:          Main.hs
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy,
                      simdy:matmul,
                      vector ^>=0.13.1.0,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1

    if flag(llvm)
        ghc-options: -fllvm

        if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
            -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
            -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
            ghc-options: -optlc -mattr=+evex512

benchmark simdy-benchmark
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   benchmark
    build-depends:    base >=4.19.0.0 && <4.24,
                      simdy,
                      simdy:matmul,
                      vector ^>=0.13.1.0,
                      tasty-bench ^>=0.4.1

    if flag(llvm)
        ghc-options: -fllvm

        if flag(avx512) && os(darwin) && impl(ghc == 9.14.1)
            -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
            -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
            ghc-options: -optlc -mattr=+evex512
