cabal-version:      3.4
name:               simdy
version:            0.1.0.0
synopsis:           Wrappers around GHC's SIMD primitives.
description:        Please see the README on GitHub at <https://github.com/minoki/haskell-simdy#readme>
license:            BSD-3-Clause
license-file:       LICENSE
author:             ARATA Mizuki
maintainer:         minorinoki@gmail.com
copyright:          2025 ARATA Mizuki
category:           Data
build-type:         Simple
extra-doc-files:    README.md
                    CHANGELOG.md
extra-source-files: cbits/mask.h
                    cbits/mask.c
                    cbits/select.c
                    cbits/bitwise.c
                    cbits/int_compare.c
                    cbits/float_compare.c
                    cbits/double_compare.c
                    cbits/int_minmax.c
                    cbits/float_minmax.c
                    cbits/float_minmaxnm.c
                    cbits/double_minmax.c
                    cbits/double_minmaxnm.c
                    cbits/fma.c

-- The versions of GHC and core libraries:
--
-- * GHC 9.6.* / base-4.18.* / ghc-prim 0.10.*
-- * GHC 9.8.* / base-4.19.* / ghc-prim 0.11.*
--     * GHC 9.8.1 and 9.8.2 are not supported because the FMA primitive is broken and I don't think it is worth working around it.
--     * GHC 9.8.1 is affected by: https://gitlab.haskell.org/ghc/ghc/-/issues/24160
--     * GHC 9.8.2 is affected by: https://gitlab.haskell.org/ghc/ghc/-/issues/24496
--     * FFI issue on AArch64: https://gitlab.haskell.org/ghc/ghc/-/issues/26907
-- * GHC 9.10.* / base-4.20.* / ghc-prim 0.12.*
--     * __GLASGOW_HASKELL_LLVM__ issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25606, fixed in 9.10.2
--     * FFI issue on AArch64: https://gitlab.haskell.org/ghc/ghc/-/issues/26907
-- * GHC 9.12.* / base-4.21.* / ghc-prim 0.13.* / ghc-internal 9.12##.* / ghc-experimental 9.12##.*
--     * I'd like to drop support for 9.12.1/9.12.2/9.12.3 once 9.12.4 is out, because of multiple issues.
--     * Broadcast issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25561, fixed in 9.12.3
--     * __GLASGOW_HASKELL_LLVM__ issue: https://gitlab.haskell.org/ghc/ghc/-/issues/25606, fixed in 9.12.3
--     * +evex512 issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26410
--     * NCG spill issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26411
-- * GHC 9.14.* / base-4.22.* / ghc-prim 0.13.* / ghc-internal 9.14##.* / ghc-experimental 9.14##.*
--     * I'd like to drop support for 9.14.1 once 9.14.2 is out, because of +evex512 and NCG spill issue.
--     * +evex512 issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26410
--     * NCG spill issue: https://gitlab.haskell.org/ghc/ghc/-/issues/26411

flag no-simd
    description: Don't use native vector types
    manual: True
    default: False

-- Setting the `avx512` flag should enable the functionality of `haswell`.
-- To achieve this, we should use `flag(haswell) || flag(avx512)` instead of just `flag(haswell)`
flag haswell
    description: Enable AVX2+FMA+F16C (Intel: Haswell or later, AMD: Zen or later). Try to use 256-bit vectors if supported by the backend.
    manual: True
    default: False

flag avx512
    description: Enable AVX-512 (F+VL+BW+DQ). Try to use 512-bit vectors if supported by the backend.
    manual: True
    default: False

flag llvm
    description: Use LLVM backend
    manual: True
    default: True

common warnings
    ghc-options: -Wall -Wcompat
    if impl(ghc >= 9.14)
        -- For Data.Simdy.Tuple
        ghc-options: -Wno-pattern-namespace-specifier

common arch-options
    if impl(ghc == 9.8.1) || impl(ghc == 9.8.2)
        -- GHC 9.8.1 has the FMA primitive broken: https://gitlab.haskell.org/ghc/ghc/-/issues/24160
        -- GHC 9.8.2 has the FMA primitive broken: https://gitlab.haskell.org/ghc/ghc/-/issues/24496
        buildable: False
    if flag(haswell) || flag(avx512)
        -- Traditionally, -mavx didn't imply -msse4.2: https://gitlab.haskell.org/ghc/ghc/-/issues/24989
        -- GHC 9.16 will have the new behavior.
        ghc-options: -msse4.2 -mavx -mavx2
        cc-options: -mavx2 -mfma -mf16c
    if (flag(haswell) || flag(avx512)) && impl(ghc >= 9.8)
        ghc-options: -mfma
    if flag(haswell) || flag(avx512) || arch(aarch64)
        cpp-options: -DUSE_FMA
    if flag(avx512)
        -- We might be able to add `ghc-options: -mavx512vl -mavx512bw -mavx512dq` on future GHC versions: https://gitlab.haskell.org/ghc/ghc/-/issues/26406
        ghc-options: -mavx512f
        cpp-options: -DUSE_AVX512
        cc-options: -mavx512f -mavx512vl -mavx512bw -mavx512dq
    if flag(llvm)
        ghc-options: -fllvm
        -- We need to detect the use of LLVM backend on GHC 9.12.{1,2} to workaround https://gitlab.haskell.org/ghc/ghc/-/issues/25561
        -- However, __GLASGOW_HASKELL_LLVM__ is not defined on GHC 9.12.1: https://gitlab.haskell.org/ghc/ghc/-/issues/25606
        -- So we define a custom macro.
        -- I'd like to drop support for these versions once 9.12.4 is out.
        if impl(ghc == 9.12.1) || impl(ghc == 9.12.2)
            cpp-options: -DBROADCAST_IS_BROKEN
    if flag(llvm) && flag(avx512) && os(darwin) && (impl(ghc == 9.12.1) || impl(ghc == 9.12.2) || impl(ghc == 9.12.3) || impl(ghc == 9.14.1))
        -- You need `-optlc -mattr=+evex512` if using GHC 9.12.{1,2,3} or 9.14.1 with LLVM 18 or newer
        -- See https://gitlab.haskell.org/ghc/ghc/-/issues/26410
        ghc-options: -optlc -mattr=+evex512

library common
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy.Class.Bits
                      Data.Simdy.Internal.Class
                      Data.Simdy.Internal.Fusible
                      Data.Simdy.Internal.Shuffle
    other-modules:    Data.Simdy.Internal.Class.Generated
                      Data.Simdy.Internal.FMA
                      Data.Simdy.Internal.PrimExtra

    -- We use separate C sources for the baseline ISA/Haswell/AVX-512 because
    --   1) We want to make sure the C sources are recompiled when we re-build this package with different flags
    --   2) We don't want to rely on __attribute__((target)) because LLVM is buggy: https://github.com/llvm/llvm-project/issues/64706
    if flag(avx512)
        c-sources:        cbits/float_minmax_avx512.c
                          cbits/float_minmaxnm_avx512.c
                          cbits/double_minmax_avx512.c
                          cbits/double_minmaxnm_avx512.c
                          cbits/mask_avx512.c
                          cbits/select_avx512.c
                          cbits/bitwise_avx512.c
                          cbits/int_compare_avx512.c
                          cbits/float_compare_avx512.c
                          cbits/double_compare_avx512.c
        if impl(ghc < 9.12)
            c-sources:    cbits/int_minmax_avx512.c
        if impl(ghc < 9.8)
            c-sources:    cbits/fma_avx512.c
    elif flag(haswell)
        c-sources:        cbits/float_minmax_haswell.c
                          cbits/float_minmaxnm_haswell.c
                          cbits/double_minmax_haswell.c
                          cbits/double_minmaxnm_haswell.c
                          cbits/mask_haswell.c
                          cbits/select_haswell.c
                          cbits/bitwise_haswell.c
                          cbits/int_compare_haswell.c
                          cbits/float_compare_haswell.c
                          cbits/double_compare_haswell.c
        if impl(ghc < 9.12)
            c-sources:    cbits/int_minmax_haswell.c
        if impl(ghc < 9.8)
            c-sources:    cbits/fma_haswell.c
    else
        c-sources:        cbits/float_minmax_baseline.c
                          cbits/float_minmaxnm_baseline.c
                          cbits/double_minmax_baseline.c
                          cbits/double_minmaxnm_baseline.c
                          cbits/mask_baseline.c
                          cbits/select_baseline.c
                          cbits/bitwise_baseline.c
                          cbits/int_compare_baseline.c
                          cbits/float_compare_baseline.c
                          cbits/double_compare_baseline.c
        if impl(ghc < 9.12)
            c-sources:    cbits/int_minmax_baseline.c
        if impl(ghc < 9.8)
            c-sources:    cbits/fma_baseline.c

    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0
    hs-source-dirs:   src-common
    default-language: GHC2021

library no-simd
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.NoSIMD
    other-modules:    Data.Simdy.Internal.NoSIMD.X2
                      Data.Simdy.Internal.NoSIMD.X4
                      Data.Simdy.Internal.NoSIMD.X8
                      Data.Simdy.Internal.NoSIMD.X16
                      Data.Simdy.Internal.NoSIMD.X32
                      Data.Simdy.Internal.NoSIMD.X64
                      Data.Simdy.Internal.NoSIMD.HalfVector
    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0,
                      simdy:common
    hs-source-dirs:   src-no-simd
    default-language: GHC2021

library vl128
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.SIMD128
                      Data.Simdy.Internal.SIMD128.Prim
                      Data.Simdy.Internal.SIMD128.PrimExtra
                      Data.Simdy.Internal.SIMD128.X2
                      Data.Simdy.Internal.SIMD128.X4
                      Data.Simdy.Internal.SIMD128.X8
                      Data.Simdy.Internal.SIMD128.X16
                      Data.Simdy.Internal.SIMD128.X32
                      Data.Simdy.Internal.SIMD128.X64
                      Data.Simdy.Internal.SIMD128.HalfVector
    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0,
                      simdy:common
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl128
    default-language: GHC2021
    if flag(no-simd) || (!flag(llvm) && (impl(ghc < 9.12) || !arch(x86_64)))
        -- vl128 requires !no-simd && (llvm || (ghc >= 9.12 && x86_64))
        buildable: False

library vl256
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.SIMD256
                      Data.Simdy.Internal.SIMD256.Prim
                      Data.Simdy.Internal.SIMD256.PrimExtra
                      Data.Simdy.Internal.SIMD256.X4
                      Data.Simdy.Internal.SIMD256.X8
                      Data.Simdy.Internal.SIMD256.X16
                      Data.Simdy.Internal.SIMD256.X32
                      Data.Simdy.Internal.SIMD256.X64
                      Data.Simdy.Internal.SIMD256.HalfVector
    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0,
                      simdy:common,
                      simdy:vl128
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl256
    default-language: GHC2021
    if flag(no-simd) || !(flag(haswell) || flag(avx512)) || !flag(llvm)
        -- vl256 requires !no-simd && (haswell || avx512) && llvm
        buildable: False

library vl512
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy.Internal.SIMD512
    other-modules:    Data.Simdy.Internal.SIMD512.Prim
                      Data.Simdy.Internal.SIMD512.PrimExtra
                      Data.Simdy.Internal.SIMD512.X8
                      Data.Simdy.Internal.SIMD512.X16
                      Data.Simdy.Internal.SIMD512.X32
                      Data.Simdy.Internal.SIMD512.X64
                      Data.Simdy.Internal.SIMD512.HalfVector
    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0,
                      simdy:common,
                      simdy:vl128,
                      simdy:vl256
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-vl512
    default-language: GHC2021
    if flag(no-simd) || !flag(avx512) || !flag(llvm)
        -- vl512 requires !no-simd && avx512 && llvm
        buildable: False

library plugin
    import:           warnings
                    , arch-options
    visibility:       public
    exposed-modules:  Data.Simdy.Shuffle.Plugin
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy:common,
                      ghc >=9.6 && <9.15,
                      ghc-tcplugin-api ^>=0.18.2
    if impl(ghc >= 9.12)
        build-depends: ghc-experimental
    hs-source-dirs:   src-plugin
    default-language: GHC2021

library
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy
                      Data.Simdy.FMA
                      Data.Simdy.Horizontal
                      Data.Simdy.Mask
                      Data.Simdy.MinMax
                      Data.Simdy.Pack
                      Data.Simdy.Shuffle
                      Data.Simdy.Split
                      Data.Simdy.Tuple
                      Data.Simdy.Vector.Bundle
                      Data.Simdy.Vector.Class
                      Data.Simdy.Vector.Generic
                      Data.Simdy.Vector.Unboxed
    reexported-modules: Data.Simdy.Class.Bits
                      , Data.Simdy.Internal.Class
                      , Data.Simdy.Internal.NoSIMD
                      , Data.Simdy.Internal.Fusible as Data.Simdy.Fusible

    if !flag(no-simd) && (flag(llvm) || (impl(ghc >= 9.12) && arch(x86_64)))
        reexported-modules: Data.Simdy.Internal.SIMD128
        build-depends: simdy:vl128
    if !flag(no-simd) && (flag(haswell) || flag(avx512)) && flag(llvm)
        reexported-modules: Data.Simdy.Internal.SIMD256
        build-depends: simdy:vl256
    if !flag(no-simd) && flag(avx512) && flag(llvm)
        reexported-modules: Data.Simdy.Internal.SIMD512
        build-depends: simdy:vl512

    -- Choose the default vector length (Data.Simdy.Internal.Default) based on the flags.
    if flag(no-simd) || (!flag(llvm) && (impl(ghc < 9.12) || !arch(x86_64)))
        mixins: simdy:no-simd (Data.Simdy.Internal.NoSIMD, Data.Simdy.Internal.NoSIMD as Data.Simdy.Internal.Default)
    elif flag(avx512) && flag(llvm)
        mixins: simdy:vl512 (Data.Simdy.Internal.SIMD512, Data.Simdy.Internal.SIMD512 as Data.Simdy.Internal.Default)
    elif flag(haswell) && flag(llvm)
        mixins: simdy:vl256 (Data.Simdy.Internal.SIMD256, Data.Simdy.Internal.SIMD256 as Data.Simdy.Internal.Default)
    else
        mixins: simdy:vl128 (Data.Simdy.Internal.SIMD128, Data.Simdy.Internal.SIMD128 as Data.Simdy.Internal.Default)

    -- other-extensions:
    build-depends:    base >=4.18.0.0 && <4.23,
                      primitive ^>=0.9.0.0,
                      vector ^>=0.13.1.0,
                      simdy:common,
                      simdy:no-simd
    hs-source-dirs:   src
    default-language: GHC2021

test-suite simdy-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1,
                      tasty-hunit ^>=0.10.2

test-suite shuffle-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test-shuffle
    main-is:          ShuffleTest.hs
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy,
                      simdy:plugin,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1,
                      tasty-hunit ^>=0.10.2
    ghc-options:      -dlint

test-suite float-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_float_minmax.c
    build-depends:    simdy

test-suite double-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_double_minmax.c
    build-depends:    simdy

library matmul
    import:           warnings
                    , arch-options
    exposed-modules:  MatMul
    hs-source-dirs:   example/matmul
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy,
                      vector ^>=0.13.1.0,
                      deepseq
    default-language: GHC2021

test-suite simdy-test-matmul
    import:           warnings
                    , arch-options
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   example/matmul-test
    main-is:          Main.hs
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy,
                      simdy:matmul,
                      vector ^>=0.13.1.0,
                      tasty ^>=1.5.3,
                      tasty-quickcheck ^>=0.11.1

benchmark simdy-benchmark
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   benchmark
    build-depends:    base >=4.18.0.0 && <4.23,
                      simdy,
                      simdy:matmul,
                      vector ^>=0.13.1.0,
                      tasty-bench ^>=0.4.1
