cabal-version:      3.0
name:               simdy
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             ARATA Mizuki
maintainer:         minorinoki@gmail.com
-- copyright:
category:           Data
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

flag no-simd
    description: Don't use native vector types
    manual: True
    default: False

flag avx2
    description: Enable 256-bit vector via AVX2 (AVX2+FMA+F16C)
    manual: True
    default: False

flag avx512
    description: Enable 512-bit vector via AVX-512 (F+VL+BW+DQ)
    manual: True
    default: False

flag llvm
    description: Use LLVM backend
    manual: True
    default: True

common warnings
    ghc-options: -Wall -Wcompat

common arch-options
    if !flag(no-simd)
        cpp-options: -DUSE_SIMD128
    if flag(avx2) || flag(avx512)
        ghc-options: -msse4.2 -mavx2
        cpp-options: -DUSE_SIMD256
        cc-options: -mavx2 -mfma -mf16c
    if flag(avx512)
        ghc-options: -mavx512f
        cpp-options: -DUSE_SIMD512 -DUSE_AVX512
        cc-options: -mavx512f -mavx512vl -mavx512bw -mavx512dq
    if flag(llvm)
        ghc-options: -fllvm

library
    import:           warnings
                    , arch-options
    exposed-modules:  Data.Simdy
                      Data.Simdy.Horizontal
                      Data.Simdy.Pack
                      Data.Simdy.Split
                      Data.Simdy.Tuple
                      Data.Simdy.Internal.Class
                      Data.Simdy.Internal.NoSIMD
                      Data.Simdy.Vector.Unboxed
    other-modules:    Data.Simdy.Internal.Class.Generated
                      Data.Simdy.Internal.PrimExtra
                      Data.Simdy.Internal.NoSIMD.X2
                      Data.Simdy.Internal.NoSIMD.X4
                      Data.Simdy.Internal.NoSIMD.X8
                      Data.Simdy.Internal.NoSIMD.X16
                      Data.Simdy.Internal.NoSIMD.X32
                      Data.Simdy.Internal.NoSIMD.HalfVector
    c-sources:        cbits/float_minmax.c
                      cbits/float_minmaxnm.c
                      cbits/double_minmax.c
                      cbits/double_minmaxnm.c
    if !flag(no-simd)
        exposed-modules:  Data.Simdy.Internal.SIMD128
        other-modules:    Data.Simdy.Internal.SIMD128.Prim
                          Data.Simdy.Internal.SIMD128.X2
                          Data.Simdy.Internal.SIMD128.X4
                          Data.Simdy.Internal.SIMD128.X8
                          Data.Simdy.Internal.SIMD128.X16
                          Data.Simdy.Internal.SIMD128.X32
                          Data.Simdy.Internal.SIMD128.HalfVector
    if flag(avx2) || flag(avx512)
        exposed-modules:  Data.Simdy.Internal.SIMD256
        other-modules:    Data.Simdy.Internal.SIMD256.Prim
                          Data.Simdy.Internal.SIMD256.X4
                          Data.Simdy.Internal.SIMD256.X8
                          Data.Simdy.Internal.SIMD256.X16
                          Data.Simdy.Internal.SIMD256.X32
                          Data.Simdy.Internal.SIMD256.HalfVector
    if flag(avx512)
        exposed-modules:  Data.Simdy.Internal.SIMD512
        other-modules:    Data.Simdy.Internal.SIMD512.Prim
                          Data.Simdy.Internal.SIMD512.X8
                          Data.Simdy.Internal.SIMD512.X16
                          Data.Simdy.Internal.SIMD512.X32
                          Data.Simdy.Internal.SIMD512.HalfVector
    -- other-extensions:
    build-depends:    base >=4.18.0.0 && <4.22,
                      primitive ^>=0.9.0.0,
                      vector ^>=0.13.1.0
    hs-source-dirs:   src
    default-language: GHC2021

test-suite simdy-test
    import:           warnings
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base >=4.18.0.0 && <4.22,
        simdy

test-suite float-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_float_minmax.c
    build-depends:    simdy

test-suite double-minmax-test
    import:           warnings
                    , arch-options
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    main-is:          cbits/test_double_minmax.c
    build-depends:    simdy
